# Q1

In [ ]:
import numpy as np 
np.arange(start=2, stop=53, step=3)



# Q2

In [ ]:
x=int(input(range (0,6)))


In [ ]:
y=int(input(range(6,11)))

In [3]:
x=int(input(range (0,6)))
import numpy as np
array=np.array(x)

range(0, 6)0 1 2 3 4 5


ValueError: invalid literal for int() with base 10: '0 1 2 3 4 5'

In [9]:
x1=[1,2,3,4,5]
print(x1)

[1, 2, 3, 4, 5]


In [10]:
y1=[6,7,8,9,10]
print(y1)

[6, 7, 8, 9, 10]


In [16]:
x1=[1,2,3,4,5]
y1=[6,7,8,9,10]
import numpy as np
array1=np.array(x1)
array2=np.array(y1)
print(array1)
print(array2)
print(array1+array2)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]


In [18]:
array1=np.array(x1)
array2=np.array(y1)
print(np.add(array1,array2))

[ 7  9 11 13 15]
